packages:
  - apps/*
  - packages/*

catalogs:
  better-auth:
    better-auth: 1.6.9
  strapi:
    '@strapi/plugin-cloud': 5.52.2
    '@strapi/provider-email-sendgrid': 5.52.2
    '@strapi/strapi': 5.52.2
    '@strapi/types': 5.52.2
    '@strapi/admin': 5.52.2
    '@strapi/typescript-utils': 5.52.2

onlyBuiltDependencies:
  - better-sqlite3
